language: ruby
bundler_args: --without development
script: 'bundle exec rspec --tag ~web_driver:true'
env:
  - TRAVIS_CI=true
rvm:
  - 1.9.3
  - 2.0.0
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
